Refactoring/16 fix paths
exasol/sphinx-github-pages-generator pull request #37
Opened 2022-08-03 11:03 UTC by MarleneKress79789

fixes #16

2022-08-03 11:25 UTC, tkilias requested changes

2022-08-03 11:25 UTC, tkilias commented on exasol_sphinx_github_pages_generator/cli.py
> +              type=str, default="doc/",
click provides also a Path type https://click.palletsprojects.com/en/8.0.x/parameters/

2022-08-03 11:25 UTC, tkilias commented on exasol_sphinx_github_pages_generator/cli.py
>  @click.option('--module-path',
click provides also a Path type https://click.palletsprojects.com/en/8.0.x/parameters/

2022-08-03 11:25 UTC, tkilias commented on exasol_sphinx_github_pages_generator/deployer.py
>      def __init__(self, source_dir: str, source_branch: str, source_origin: str, current_commit_id: str,
Can you sue pathlib.Path also with source_dir?

2022-08-03 11:25 UTC, tkilias commented on exasol_sphinx_github_pages_generator/deployer.py
> +        os.chdir(f"./{self.source_dir}")
Is this relative to current working dir=

2022-08-03 11:25 UTC, tkilias commented on tests/test_deploy_github_pages.py
> +    result = CliRunner().invoke(cli.main, args_list)
The invoke function has a catch_excecptions option, see https://click.palletsprojects.com/en/7.x/api/#click.testing.CliRunner.invoke 
You can than ask the return value of invoke, for the exception with the exception property

2022-08-03 11:25 UTC, tkilias commented on noxfile.py
> +    session.run("pytest", "--pdb", f"{PROJECT_ROOT / 'tests'}")
for what do you need --pdb

2022-08-04 08:12 UTC, MarleneKress79789 commented on noxfile.py
> +    session.run("pytest", "--pdb", f"{PROJECT_ROOT / 'tests'}")
i dont, forgott to remove it

2022-08-22 10:15 UTC, tkilias requested changes

2022-08-22 10:15 UTC, tkilias commented on exasol_sphinx_github_pages_generator/cli.py
> +            print(sys.exc_info()[2])
is this a debug output? if yes, please remove, otherwise make more clear what you want to output

2022-08-22 10:21 UTC, tkilias approved these changes

2022-08-22 10:24 UTC, merged